# Generated by Django 3.2.6 on 2021-08-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210831_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code_self',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_by_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='referral code'),
        ),
    ]
