# Generated by Django 3.2.6 on 2021-08-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_referrals_referred_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code_self',
            field=models.CharField(max_length=8, unique=True, verbose_name='My Referral Code'),
        ),
    ]
