# Generated by Django 3.2.6 on 2021-08-31 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_user_referral_code_self'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='referred_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
