# Generated by Django 3.2.6 on 2021-09-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_referrals_referred_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referrals',
            old_name='referred_to_inc',
            new_name='referred_by_inc',
        ),
        migrations.RemoveField(
            model_name='referrals',
            name='referred_to',
        ),
        migrations.AddField(
            model_name='referrals',
            name='referred_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='authapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code_self',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='My Referral Code'),
        ),
    ]
